theme: jekyll-theme-midnight
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5889036558691631",
    enable_page_level_ads: true
  });
</script>